name: Deploy Code via Pull (Main & Development)

on:
  push:
    branches:
      - main
      - development  # Trigger on both 'main' and 'development' branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y ssh

    - name: Add SSH private key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull latest code based on branch
      run: |
        # Check the branch name and run the appropriate deployment based on the branch
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "Deploying to production server (main branch)"
          ssh -o StrictHostKeyChecking=no ubuntu@3.110.48.193 "
            cd /var/www/html/angular-social-network &&
            git checkout main &&
            git pull origin main"
        elif [ "${{ github.ref }}" == "refs/heads/development" ]; then
          echo "Deploying to development server (development branch)"
          ssh -o StrictHostKeyChecking=no ubuntu@3.110.48.193 "
            cd /var/www/html/angular-social-network &&
            git checkout development &&
            git pull origin development"
        else
          echo "No matching branch for deployment"
        fi
      shell: bash
